language: php
php:
- 5.5
- 5.4
- hhvm

before_script:
- wget https://scrutinizer-ci.com/ocular.phar
- composer config
- composer install

script:
- phpunit

after_script:
 - php ocular.phar code-coverage:upload --format=php-clover coverage.clover